version: "3"
services:
  missile-launcher:
    build: .
    ports: 
      - ${PORT}:${PORT}
    env_file: .env
    devices:
      - "/dev/usb/hiddev0:/dev/ttyUSB0"
    privileged: true # Should not be needed but USB control transfers doesn't work in unprivileged for some reason... Maybe needs to claim an interface?
